server:
  port: 9000
spring:
  cloud:
    gateway:
      default-filters:
        - name: RewritePath
          args:
            regexp: '/(.*)'
            replacement: '/$1'
      routes:
        - id: echoService
          uri: lb://ECHOSERVICE
          predicates:
            - Path=/echo/**
          filters:
            - StripPrefix=1
            - Customer=asdf11111111
        - id: consumerEchoService
          uri: lb://CONSUMERECHOSERVICE
          predicates:
            - Path=/consumerEcho/**
          filters:
            - StripPrefix=1
resilience4j:
  circuitbreaker:
    instances:
      CircuitBreakerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
