server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: redireccion_a_8091
          uri: http://localhost:8091
          predicates:
            - Path=/**
          filters:
            - RedirectTo=301, http://localhost:8091
eureka:
  client:
    fetchRegistry: false  # Desactivar la búsqueda de registros, porque es un servidor Eureka
    registerWithEureka: false  # Desactivar el registro en este servidor
