server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: redireccion_a_8091
          uri: http://localhost:8091
          predicates:
            - Path=/echo/**
          filters:
            - StripPrefix=1
