server:
  port: 9000
spring:
  cloud:
    gateway:
      default-filters:
        - name: RewritePath
          args:
            regexp: '/(.*)'
            replacement: '/$1'
      routes:
        - id: echoService
          uri: lb://ECHOSERVICE
          predicates:
            - Path=/echo/**
          filters:
            - StripPrefix=1
            - Customer=asdf11111111
        - id: consumerEchoService
          uri: lb://CONSUMERECHOSERVICE
          predicates:
            - Path=/consumerEcho/**
          filters:
            - StripPrefix=1
