server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: echoService
          uri: lb://ECHOSERVICE
          predicates:
            - Path=/echo/**
          filters:
            - StripPrefix=1
        - id: consumerEchoService
          uri: lb://consumerEchoService
          predicates:
            - Path=/consumerEcho/**
          filters:
            - StripPrefix=1
