server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: redireccion_a_8091
          uri: http://localhost:8091
          predicates:
            - Path=/**
          filters:
            - RedirectTo=301, http://localhost:8091
      discovery:
        enabled: true
        locator:
          enabled: true
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
